apiVersion: v1
kind: Namespace
metadata:
  name: astro-financial
  labels:
    name: astro-financial
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: astro-financial-quota
  namespace: astro-financial
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"