apiVersion: v1
kind: Pod
metadata:
  name: postgres-debug
  namespace: time-series-indexing
  labels:
    app: postgres-debug
spec:
  containers:
  - name: postgres-client
    image: postgres:15
    command: ["sleep", "3600"]
    env:
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: market-encoder-secrets
          key: db-host
    - name: PGPORT
      value: "5432"
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          name: market-encoder-secrets
          key: db-name
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: market-encoder-secrets
          key: db-user
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: market-encoder-secrets
          key: db-password
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"
  restartPolicy: Never