apiVersion: batch/v1
kind: Job
metadata:
  name: market-encoder-test
  namespace: time-series-indexing
  labels:
    app: market-encoder
    component: test-job
spec:
  template:
    metadata:
      labels:
        app: market-encoder
        component: test-job
    spec:
      containers:
      - name: market-encoder-test
        image: 928440193005.dkr.ecr.us-west-1.amazonaws.com/market-encoder:latest
        imagePullPolicy: Always
        command:
        - python
        - scripts/simple_daily_encoding.py
        - --config
        - /app/config/securities_simple.yaml
        - --verbose
        env:
        # Database connection
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: market-encoder-secrets
              key: db-host
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: market-encoder-secrets
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: market-encoder-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: market-encoder-secrets
              key: db-password
        # Application settings
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: simple-market-encoder-config
      restartPolicy: Never
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
  backoffLimit: 3