apiVersion: v1
kind: Secret
metadata:
  name: market-encoder-secrets
  namespace: time-series-indexing
  labels:
    app: market-encoder
    component: secrets
type: Opaque
stringData:
  db-host: "financial-postgres.cvkuccacyqwr.us-west-1.rds.amazonaws.com"
  db-name: "financial-postgres"
  db-user: "postgres"
  db-password: "REPLACE_WITH_ACTUAL_PASSWORD"  # Copy this file to market-encoder-secrets.yaml and set real password