---
# Backfill Service - Docker-based deployment with Swiss Ephemeris
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backfill-service
  namespace: time-series-indexing
  labels:
    app: backfill-service
    version: v2
    deployment-type: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backfill-service
  template:
    metadata:
      labels:
        app: backfill-service
        version: v2
        deployment-type: docker
    spec:
      containers:
        - name: backfill-service
          image: 928440193005.dkr.ecr.us-west-1.amazonaws.com/astrofinancial-backfill-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
              protocol: TCP

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: market-encoder-secrets
                  key: db-host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: market-encoder-secrets
                  key: db-user
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: market-encoder-secrets
                  key: db-name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: market-encoder-secrets
                  key: db-password
            - name: DB_PORT
              value: "5432"
            - name: SERVICE_NAME
              value: "backfill-service"
            - name: PYTHONPATH
              value: "/app/src"
            - name: FRED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fred-api-secret
                  key: api-key
            # ChromaDB Cloud configuration
            - name: CHROMA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: api-key
            - name: CHROMA_TENANT
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: tenant
            - name: CHROMA_DATABASE
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: database
            - name: CHROMA_CONNECTION_TYPE
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: use-hosted

          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Resource limits
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false

      restartPolicy: Always

---
# Service to expose the backfill service
apiVersion: v1
kind: Service
metadata:
  name: backfill-service
  namespace: time-series-indexing
  labels:
    app: backfill-service
    deployment-type: docker
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: backfill-service
