apiVersion: v1
kind: Secret
metadata:
  name: anthropic-secret
  namespace: time-series-indexing
  labels:
    app: llm-services
    component: secrets
type: Opaque
stringData:
  api-key: "REPLACE_WITH_ACTUAL_ANTHROPIC_API_KEY"  # Copy this file to anthropic-secret.yaml and set real API key